# Generated by Django 3.1.6 on 2021-07-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210704_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household_filters',
            name='About',
        ),
        migrations.RemoveField(
            model_name='household_filters',
            name='Fitting',
        ),
        migrations.RemoveField(
            model_name='household_filters',
            name='For_enclosures',
        ),
        migrations.RemoveField(
            model_name='household_filters',
            name='For_flasks',
        ),
        migrations.RemoveField(
            model_name='household_filters',
            name='Form',
        ),
        migrations.RemoveField(
            model_name='household_filters',
            name='Interface_language',
        ),
        migrations.RemoveField(
            model_name='household_filters',
            name='Performance',
        ),
        migrations.RemoveField(
            model_name='household_filters',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='household_filters',
            name='Value',
        ),
        migrations.RemoveField(
            model_name='household_filters',
            name='Vendor',
        ),
        migrations.RemoveField(
            model_name='household_filters',
            name='View',
        ),
        migrations.RemoveField(
            model_name='household_filters',
            name='Volume',
        ),
        migrations.AddField(
            model_name='household_filters',
            name='Color',
            field=models.CharField(blank=True, choices=[('Белый', 'Белый'), ('Красный', 'Красный'), ('Прозрачный', 'Прозрачный'), ('Синий', 'Синий'), ('Стальной', 'Стальной')], max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='household_filters',
            name='Cartridge_size',
            field=models.CharField(blank=True, choices=[('прочее', 'прочее'), ('BB 10', 'BB 10'), ('BB 20', 'BB 20'), ('SL 5', 'SL 5'), ('SL 10', 'SL 10'), ('SL 20', 'SL 20'), ('SL 30', 'SL 30'), ('SL 40', 'SL 40')], max_length=50, verbose_name='Размер картриджа'),
        ),
        migrations.AlterField(
            model_name='household_filters',
            name='For_systems',
            field=models.CharField(blank=True, choices=[('Бустерные насосы (помпы)', 'Бустерные насосы (помпы)'), ('Краны', 'Краны'), ('Мембранные баки', 'Мембранные баки'), ('Постфильтры и паки', 'Постфильтры и паки'), ('Прочее', 'Прочее')], max_length=50, verbose_name='Для систем'),
        ),
        migrations.AlterField(
            model_name='household_filters',
            name='Microtity',
            field=models.CharField(blank=True, choices=[('не измеряется', 'не измеряется'), ('0,5', '0,5'), ('1', '1'), ('5', '5'), ('10', '10'), ('20', '20'), ('25', '25'), ('50', '50'), ('100', '100')], max_length=50, verbose_name='Микронность'),
        ),
        migrations.AlterField(
            model_name='household_filters',
            name='PrType',
            field=models.CharField(blank=True, choices=[('Аксессуары и запчасти', 'Аксессуары и запчасти'), ('Прочее', 'Прочее'), ('Осмос', 'Осмос'), ('Система', 'Система'), ('Фильтр от накипи', 'Фильтр от накипи'), ('Контейнер под загрузку', 'Контейнер под загрузку'), ('Механической очистки', 'Механической очистки'), ('Обезжелезивания и деманганации', 'Обезжелезивания и деманганации'), ('Угольный гранулированный', 'Угольный гранулированный'), ('Угольный прессованый', 'Угольный прессованый'), ('Умягчения', 'Умягчения'), ('корпуса для осмосов', 'корпуса для осмосов'), ('обратноосмотические мембраны', 'обратноосмотические мембраны'), ('2-х и 3-х ходовые клапана', '2-х и 3-х ходовые клапана'), ('Запчасти и комплектующие', 'Запчасти и комплектующие'), ('Инжектора', 'Инжектора'), ('Комплектующие (ПВХ и т. п.)', 'Комплектующие (ПВХ и т. п.)'), ('Комплектующие осмос', 'Комплектующие осмос'), ('Тарировочные шайбы', 'Тарировочные шайбы'), ('Емкость', 'Емкость'), ('Комплектующие', 'Комплектующие'), ('для дозации', 'для дозации'), ('Копмплектующие и запчасти', 'Копмплектующие и запчасти'), ('Марганцовочный', 'Марганцовочный'), ('Солевой', 'Солевой'), ('Импульсные', 'Импульсные'), ('Аналоговые', 'Аналоговые'), ('Цифровые', 'Цифровые'), ('Верхние дистрибьюторы и распред. системы', 'Верхние дистрибьюторы и распред. системы'), ('Нижние дистрибьюторы и распред. системы', 'Нижние дистрибьюторы и распред. системы'), ('Трубы', 'Трубы'), ('Миксы', 'Миксы'), ('Осветление/обезжелезивание', 'Осветление/обезжелезивание'), ('Смолы', 'Смолы'), ('Сорбция', 'Сорбция'), ('Химия и реагенты', 'Химия и реагенты'), ('Безреагентный - автоматический', 'Безреагентный - автоматический'), ('Безреагентный - ручной', 'Безреагентный - ручной'), ('Реагентный - автоматический', 'Реагентный - автоматический'), ('Реагентный - ручной', 'Реагентный - ручной'), ('Аксессуары', 'Аксессуары'), ('Корпуса (для гор. воды)', 'Корпуса (для гор. воды)'), ('Корпуса (для хол. воды)', 'Корпуса (для хол. воды)'), ('комплектующие', 'комплектующие'), ('Напорная аэрация', 'Напорная аэрация'), ('вертикальный', 'вертикальный'), ('горизонтальный', 'горизонтальный'), ('Запчасти', 'Запчасти')], max_length=50, verbose_name='Тип'),
        ),
    ]
