# Generated by Django 3.1.6 on 2021-07-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210704_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='household_filters',
            name='About',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='household_filters',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household_filters',
            name='Value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='household_filters',
            name='Size',
            field=models.CharField(blank=True, choices=[('1812', '1812'), ('2012', '2012'), ('2521', '2521'), ('2540', '2540'), ('2812', '2812'), ('3012', '3012'), ('4021', '4021'), ('4040', '4040'), ('8040', '8040'), ('BB 10', 'BB 10'), ('BB 20', 'BB 20'), ('SL 5', 'SL 5'), ('SL 10', 'SL 10'), ('SL 20', 'SL 20'), ('SL 30', 'SL 30'), ('SL 40', 'SL 40')], max_length=50, verbose_name='Размер'),
        ),
    ]
