# Generated by Django 3.1.6 on 2021-07-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_household_filters_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='household_filters',
            name='Vendor',
            field=models.CharField(choices=[('Aqua', 'Aqua'), ('Aquapro', 'Aquapro'), ('Autotrol', 'Autotrol'), ('AWT', 'AWT'), ('Canature', 'Canature'), ('Cepex', 'Cepex'), ('Cintropur', 'Cintropur'), ('Clack', 'Clack'), ('CNP', 'CNP'), ('CSM', 'CSM'), ('Ecosoft', 'Ecosoft'), ('ELITECH', 'ELITECH'), ('Euraqua', 'Euraqua'), ('Filmtec', 'Filmtec'), ('Fleck', 'Fleck'), ('Grundfos', 'Grundfos'), ('Mytho', 'Mytho'), ('NanoRo', 'NanoRo'), ('NatureWater', 'NatureWater'), ('NOCCHI', 'NOCCHI'), ('Noname', 'Noname'), ('Noyi', 'Noyi'), ('Pentair', 'Pentair'), ('Philips', 'Philips'), ('Pimtas', 'Pimtas'), ('Runxin', 'Runxin'), ('Seko', 'Seko'), ('STRUCTURAL', 'STRUCTURAL'), ('Vontron', 'Vontron'), ('Wave Cyber', 'Wave Cyber'), ('Zenner', 'Zenner'), ('Аргеллит', 'Аргеллит'), ('ЕВРОПА', 'ЕВРОПА'), ('ИНДИЯ', 'ИНДИЯ'), ('КИТАЙ', 'КИТАЙ'), ('КОРЕЯ', 'КОРЕЯ'), ('РОССИЯ', 'РОССИЯ'), ('США', 'США'), ('Тайвань', 'Тайвань')], default=0, max_length=50, verbose_name='Производитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='household_filters',
            name='Category',
            field=models.CharField(choices=[('191', 'Колбы BB (Aquapro)'), ('192', 'Колбы SL (Aquapro)'), ('193', 'Баки (Aquapro)'), ('140', 'Бустерные насосы (Aquapro)'), ('196', 'Запчасти (Aquapro)'), ('197', 'Картриджи механической очистки (Aquapro)'), ('198', 'Картриджи угольные (Aquapro)'), ('195', 'Мембраны, постфильтры (Aquapro)'), ('199', 'Бытовые системы обратного осмоса (Aquapro)'), ('271', 'Canature'), ('223', 'Запчасти (NatureWater)'), ('221', 'Колбы BB (NatureWater)'), ('222', 'Колбы SL (NatureWater)'), ('219', 'Картриджи (NatureWater)'), ('226', 'Постфильтры (NatureWater)'), ('225', 'Бытовые системы водоочистки (NatureWater)'), ('133', 'Картриджи Аргумент, колбы Housing, Vontron'), ('25', 'Картриджи механической очистки (Аргумент)'), ('26', 'Картриджи угольные, умягчения, обезжелезивания (Аргумент)'), ('27', 'Колoбы Housing'), ('28', 'Мембраны Vontron и Canature')], max_length=50, verbose_name='Категория'),
        ),
    ]
