# Generated by Django 3.1.6 on 2021-08-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210801_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=120)),
                ('pr_category_id', models.CharField(max_length=120)),
                ('pr_id', models.CharField(max_length=120)),
                ('pr_value', models.IntegerField()),
            ],
        )
    ]
