# Generated by Django 3.2.5 on 2021-07-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20210712_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='For_enclosures',
            field=models.CharField(blank=True, choices=[('0817-3672', '0817-3672'), ('4272-6386', '4272-6386'), ('4272-6386', '4272-6386')], max_length=50, verbose_name='Для корпусов'),
        ),
        migrations.AddField(
            model_name='components',
            name='Form',
            field=models.CharField(blank=True, choices=[('горизонтальная', 'горизонтальная'), ('круглая', 'круглая'), ('прямоугольная', 'прямоугольная')], max_length=50, verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='components',
            name='Interface_language',
            field=models.CharField(blank=True, choices=[('Английский', 'Английский'), ('Русский', 'Русский')], max_length=50, verbose_name='Язык интерфейса'),
        ),
        migrations.AddField(
            model_name='components',
            name='Neck',
            field=models.CharField(blank=True, choices=[('2,5"-0', '2,5"-0'), ('4"-0', '4"-0'), ('4"-4inch', '4"-4inch'), ('6"-6inch (фланцы)', '6"-6inch (фланцы)')], max_length=50, verbose_name='Горловина'),
        ),
        migrations.AddField(
            model_name='components',
            name='View',
            field=models.CharField(blank=True, choices=[('Бок. посадка', 'Бок. посадка'), ('Стандарт', 'Стандарт')], max_length=50, verbose_name='Вид'),
        ),
        migrations.AddField(
            model_name='components',
            name='Volume',
            field=models.CharField(blank=True, choices=[('1000 л', '1000 л'), ('10000 л', '10000 л'), ('120 л', '120 л'), ('1250 л', '1250 л'), ('15000 л', '15000 л'), ('200 л', '200 л'), ('2000 л', '2000 л'), ('210 л', '210 л'), ('250 л', '250 л'), ('3000 л', '3000 л'), ('330 л', '330 л'), ('440 л', '440 л'), ('500 л', '500 л'), ('5000 л', '5000 л'), ('550 л', '550 л'), ('700 л', '700 л'), ('780 л', '780 л'), ('8000 л', '8000 л'), ('100 л', '100 л'), ('140 л', '140 л'), ('145 л', '145 л'), ('60 л', '65 л'), ('70 л', '70 л'), ('750 л', '750 л')], max_length=50, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='components',
            name='Category',
            field=models.CharField(choices=[('71', 'Баки реагентные'), ('56', 'Аксессуары (CLACK)'), ('55', 'Блоки управления (CLACK)'), ('23', 'Аксессуары (Euraqua EQ, Сlack CE, RR (RUS))'), ('267', 'Блоки управления (Euraqua EQ, Сlack CE, RR (RUS))'), ('57', 'Аксессуары (FLECK)'), ('58', 'Блоки управления (FLECK)'), ('59', 'Аксессуары (RUNXIN)'), ('60', 'Блоки управления (RUNXIN)'), ('108', 'Дозирующее оборудование Aqua'), ('212', 'Дозирующее оборудование Mytho'), ('110', 'Дозирующее оборудование SEKO'), ('112', 'Ёмкости для растворов'), ('38', 'ДРС'), ('46', 'Aquapro (на гор. воду)'), ('44', 'Canature'), ('43', 'Noyi'), ('49', 'STRUCTURAL'), ('45', 'Термо чехлы')], max_length=50, verbose_name='Категория'),
        ),
    ]
