# Generated by Django 3.1.6 on 2021-08-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20210801_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='pr_category',
            new_name='pr_category_id',
        )
    ]
