# Generated by Django 3.1.6 on 2021-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20210803_1908'),
    ]

    operations = [
        
    ]
