# Generated by Django 3.1.6 on 2021-10-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210805_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120, verbose_name='Название')),
                ('Image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('Requirements', models.TextField(verbose_name='Требование к воде')),
            ],
            options={
                'verbose_name': 'Готовые решения',
                'verbose_name_plural': 'Готовые решения',
            },
        ),
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина пользователя (системное)', 'verbose_name_plural': 'Корзина пользователя (системное)'},
        ),
        migrations.AlterModelOptions(
            name='coarse_filters',
            options={'verbose_name': 'Фильтры грубой очистки', 'verbose_name_plural': 'Фильтры грубой очистки'},
        ),
        migrations.AlterModelOptions(
            name='components',
            options={'verbose_name': 'Комплектующие', 'verbose_name_plural': 'Комплектующие'},
        ),
        migrations.AlterModelOptions(
            name='filter_materials',
            options={'verbose_name': 'Фильтрующие материалы', 'verbose_name_plural': 'Фильтрующие материалы'},
        ),
        migrations.AlterModelOptions(
            name='household_filters',
            options={'verbose_name': 'Бытовые фильтры', 'verbose_name_plural': 'Бытовые фильтры'},
        ),
        migrations.AlterModelOptions(
            name='kits',
            options={'verbose_name': 'Комплекты', 'verbose_name_plural': 'Комплекты'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='optional_equipment',
            options={'verbose_name': 'Дополнительное оборудование', 'verbose_name_plural': 'Дополнительное оборудование'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='osmosis_and_ultrafiltration',
            options={'verbose_name': 'Осмосы и Ультрафильтрация', 'verbose_name_plural': 'Осмосы и Ультрафильтрация'},
        ),
        migrations.AlterModelOptions(
            name='ultraviolet_sterilizers',
            options={'verbose_name': 'УФ стерилизаторы', 'verbose_name_plural': 'УФ стерилизаторы'},
        ),
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
