# Generated by Django 3.1.6 on 2021-10-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20211022_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('Image', models.ImageField(upload_to='index_slider/', verbose_name='Изображение')),
                ('Link', models.CharField(max_length=120, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.AlterField(
            model_name='solutions',
            name='Image',
            field=models.ImageField(upload_to='solutions/', verbose_name='Изображение'),
        ),
    ]
